"""
run_agentic.py — AtomAgents Exp2 (agentic / observe_only) with vanilla MegaMmap.

AtomAgents' dominant I/O is loading LLM model weights (safetensor / PyTorch
checkpoint files).  Unlike DeepDriveMD, there is no single numpy hotspot to
monkey-patch; instead we rely on Hermes' transparent POSIX interceptor
(LD_PRELOAD) so that all file I/O from the child process — including mmap
calls from transformers — goes through MegaMmap's tiered buffer pool.

Because LD_PRELOAD must be set before the dynamic linker runs, this script
re-launches cluster_atomagents_exp2.py as a subprocess with the correct
environment.  MetricsCollector runs in the parent and measures system-wide
wall time, peak DRAM %, and avg CPU %.

Usage
-----
    # With Hermes transparent mode (recommended):
    HERMES_INTERCEPTOR=/path/to/libhermes_posix.so \
    MEGA_WINDOW=4g \
    python run_agentic.py [-- <cluster_atomagents_exp2 args>]

    # Without Hermes (metrics only, no MegaMmap buffering):
    python run_agentic.py [-- <cluster_atomagents_exp2 args>]

Environment variables
---------------------
    HERMES_INTERCEPTOR   path to Hermes POSIX interceptor .so
                         (default: empty → Hermes not injected)
    HERMES_CONF          path to hermes.yaml config
                         (default: auto-generated from MEGA_WINDOW)
    MEGA_WINDOW          buffer pool size string, e.g. "256m" or "4g"
                         (default: "256m")
    MEGA_WORKDIR         scratch dir for Hermes config/temp files
                         (default: /tmp/mega_atomagents)

Flags
-----
    --stats-csv          where to append stats_dict row (default: stats_dict.csv)
    --window-gb          window size in GB for the CSV record
    --nprocs             number of parallel workers (default: 1)
    --                   everything after is forwarded to cluster_atomagents_exp2.py
"""
from __future__ import annotations

import argparse
import os
import subprocess
import sys
import tempfile
from pathlib import Path

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE.parent.parent))  # agent_hpc root
sys.path.insert(0, str(_HERE.parent))          # mega_mmap_integration root

from common.metrics import MetricsCollector

# Path to the upstream AtomAgents Exp2 entry-point
_EXP2_SCRIPT = (
    _HERE.parent.parent / "runtime" / "demo" / "cluster_atomagents_exp2.py"
)


def _parse_window_gb(window_str: str) -> float:
    s = window_str.strip().lower()
    if s.endswith("g"):
        return float(s[:-1])
    if s.endswith("m"):
        return float(s[:-1]) / 1024
    if s.endswith("k"):
        return float(s[:-1]) / (1024 ** 2)
    return float(s) / (1024 ** 3)


def _make_hermes_conf(window_str: str, workdir: Path) -> Path:
    """
    Write a minimal hermes.yaml with the given buffer pool size.
    The Hermes POSIX interceptor reads HERMES_CONF to configure its pool.
    """
    workdir.mkdir(parents=True, exist_ok=True)
    conf_path = workdir / "hermes.yaml"
    conf_path.write_text(
        f"# Auto-generated by run_agentic.py\n"
        f"stop_daemon: false\n"
        f"buffer_pool_ram_size: {window_str}\n"
        f"mount_points: []\n"
    )
    return conf_path


def main() -> None:
    # Split args at '--' so everything after is forwarded to exp2
    if "--" in sys.argv:
        split = sys.argv.index("--")
        my_argv   = sys.argv[1:split]
        fwd_argv  = sys.argv[split + 1:]
    else:
        my_argv  = sys.argv[1:]
        fwd_argv = []

    ap = argparse.ArgumentParser(
        description="AtomAgents Exp2 agentic + vanilla MegaMmap")
    ap.add_argument("--stats-csv", default="stats_dict.csv")
    ap.add_argument("--window-gb", type=float, default=None)
    ap.add_argument("--nprocs", type=int, default=1)
    ap.add_argument("--no-mega", action="store_true",
                    help="Skip Hermes injection; record as agentic-nomega control")
    args = ap.parse_args(my_argv)

    window_str = os.environ.get("MEGA_WINDOW", "256m")
    window_gb  = args.window_gb or _parse_window_gb(window_str)
    workdir    = Path(os.environ.get("MEGA_WORKDIR", "/tmp/mega_atomagents"))

    # Build child environment
    child_env = os.environ.copy()

    use_mega = not args.no_mega
    interceptor = os.environ.get("HERMES_INTERCEPTOR", "") if use_mega else ""
    if use_mega and interceptor and Path(interceptor).exists():
        hermes_conf = os.environ.get("HERMES_CONF", "")
        if not hermes_conf:
            hermes_conf = str(_make_hermes_conf(window_str, workdir))
            child_env["HERMES_CONF"] = hermes_conf

        existing_preload = child_env.get("LD_PRELOAD", "")
        child_env["LD_PRELOAD"] = (
            f"{interceptor}:{existing_preload}" if existing_preload
            else interceptor
        )
        print(f"[run_agentic] Hermes interceptor: {interceptor}")
        print(f"[run_agentic] HERMES_CONF: {hermes_conf}")
    else:
        if use_mega and interceptor:
            print(f"[run_agentic] WARNING: HERMES_INTERCEPTOR not found at {interceptor!r}",
                  file=sys.stderr)
        label = "nomega (control)" if args.no_mega else "no Hermes interceptor"
        print(f"[run_agentic] Running WITHOUT Hermes interception ({label})")

    # Build child command
    cmd = [
        sys.executable, str(_EXP2_SCRIPT),
        "--runtime-mode", "observe_only",
    ] + fwd_argv

    print(f"[run_agentic] Launching: {' '.join(cmd)}")

    mc = MetricsCollector()
    mc.start()
    try:
        result = subprocess.run(cmd, env=child_env)
        if result.returncode != 0:
            print(f"[run_agentic] child exited with code {result.returncode}",
                  file=sys.stderr)
    finally:
        mc.stop()

    variant = "agentic-nomega" if args.no_mega else "agentic-mega"
    mc.write_csv(
        args.stats_csv,
        app="AtomAgents",
        variant=variant,
        nprocs=args.nprocs,
        window_size_gb=window_gb,
    )


if __name__ == "__main__":
    main()
