"""
run_noai.py — AtomAgents Exp2 (non-agentic / baseline) with vanilla MegaMmap.

Same structure as run_agentic.py but uses --runtime-mode baseline, which
drives LAMMPS screw-dislocation simulations without LLM steering.  Hermes
transparent mode is still applied so that any file I/O from the child process
(including LAMMPS potential / dump files) goes through MegaMmap's buffer pool.

Usage
-----
    HERMES_INTERCEPTOR=/path/to/libhermes_posix.so \
    MEGA_WINDOW=4g \
    python run_noai.py [-- <cluster_atomagents_exp2 args>]

Environment variables
---------------------
    HERMES_INTERCEPTOR   path to Hermes POSIX interceptor .so
    HERMES_CONF          path to hermes.yaml (auto-generated if absent)
    MEGA_WINDOW          buffer pool size (default: "256m")
    MEGA_WORKDIR         scratch dir (default: /tmp/mega_atomagents)
"""
from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE.parent.parent))
sys.path.insert(0, str(_HERE.parent))

from common.metrics import MetricsCollector

_EXP2_SCRIPT = (
    _HERE.parent.parent / "runtime" / "demo" / "cluster_atomagents_exp2.py"
)


def _parse_window_gb(window_str: str) -> float:
    s = window_str.strip().lower()
    if s.endswith("g"):
        return float(s[:-1])
    if s.endswith("m"):
        return float(s[:-1]) / 1024
    if s.endswith("k"):
        return float(s[:-1]) / (1024 ** 2)
    return float(s) / (1024 ** 3)


def _make_hermes_conf(window_str: str, workdir: Path) -> Path:
    workdir.mkdir(parents=True, exist_ok=True)
    conf_path = workdir / "hermes.yaml"
    conf_path.write_text(
        f"# Auto-generated by run_noai.py\n"
        f"stop_daemon: false\n"
        f"buffer_pool_ram_size: {window_str}\n"
        f"mount_points: []\n"
    )
    return conf_path


def main() -> None:
    if "--" in sys.argv:
        split = sys.argv.index("--")
        my_argv  = sys.argv[1:split]
        fwd_argv = sys.argv[split + 1:]
    else:
        my_argv  = sys.argv[1:]
        fwd_argv = []

    ap = argparse.ArgumentParser(
        description="AtomAgents Exp2 non-agentic + vanilla MegaMmap")
    ap.add_argument("--stats-csv", default="stats_dict.csv")
    ap.add_argument("--window-gb", type=float, default=None)
    ap.add_argument("--nprocs", type=int, default=1)
    args = ap.parse_args(my_argv)

    window_str = os.environ.get("MEGA_WINDOW", "256m")
    window_gb  = args.window_gb or _parse_window_gb(window_str)
    workdir    = Path(os.environ.get("MEGA_WORKDIR", "/tmp/mega_atomagents"))

    child_env = os.environ.copy()

    interceptor = os.environ.get("HERMES_INTERCEPTOR", "")
    if interceptor and Path(interceptor).exists():
        hermes_conf = os.environ.get("HERMES_CONF", "")
        if not hermes_conf:
            hermes_conf = str(_make_hermes_conf(window_str, workdir))
            child_env["HERMES_CONF"] = hermes_conf

        existing_preload = child_env.get("LD_PRELOAD", "")
        child_env["LD_PRELOAD"] = (
            f"{interceptor}:{existing_preload}" if existing_preload
            else interceptor
        )
        print(f"[run_noai] Hermes interceptor: {interceptor}")
        print(f"[run_noai] HERMES_CONF: {hermes_conf}")
    else:
        if interceptor:
            print(f"[run_noai] WARNING: HERMES_INTERCEPTOR not found at {interceptor!r}",
                  file=sys.stderr)
        print("[run_noai] Running WITHOUT Hermes interception (metrics only)")

    cmd = [
        sys.executable, str(_EXP2_SCRIPT),
        "--runtime-mode", "baseline",
    ] + fwd_argv

    print(f"[run_noai] Launching: {' '.join(cmd)}")

    mc = MetricsCollector()
    mc.start()
    try:
        result = subprocess.run(cmd, env=child_env)
        if result.returncode != 0:
            print(f"[run_noai] child exited with code {result.returncode}",
                  file=sys.stderr)
    finally:
        mc.stop()

    mc.write_csv(
        args.stats_csv,
        app="AtomAgents",
        variant="noai-mega",
        nprocs=args.nprocs,
        window_size_gb=window_gb,
    )


if __name__ == "__main__":
    main()
